koldovsky/orlp-server

- src/main/java/com/softserve/academy/spaced/repetition/Application.java
- src/main/java/com/softserve/academy/spaced/repetition/domain/Course.java
- src/main/java/com/softserve/academy/spaced/repetition/domain/Folder.java
- src/main/resources/application.yml
> Fixed10000$Bag

- src/main/java/com/softserve/academy/spaced/repetition/controller/ManageUserController.java
- src/main/java/com/softserve/academy/spaced/repetition/repository/DeckRepository.java
- src/main/java/com/softserve/academy/spaced/repetition/service/UserService.java
As Admin I want to be able to delete existing Deck from the User's folder except his/her own Decks
> As Admin I want to be able to delete existing Deck

- src/main/java/com/softserve/academy/spaced/repetition/controller/CardController.java
- src/main/java/com/softserve/academy/spaced/repetition/service/CardService.java
Backend functionality for card deletion was added.
> VK/ORLP-169-BackendCardDeletion 

- .gitignore
- src/main/java/com/softserve/academy/spaced/repetition/DTO/impl/DeckRatingPublicDTO.java
- src/main/java/com/softserve/academy/spaced/repetition/controller/CardRatingController.java
- src/main/java/com/softserve/academy/spaced/repetition/controller/DeckRatingController.java
- src/main/java/com/softserve/academy/spaced/repetition/domain/DeckRating.java
- src/main/java/com/softserve/academy/spaced/repetition/logger/logs/log.txt
- src/main/java/com/softserve/academy/spaced/repetition/repository/CardRatingRepository.java
- src/main/java/com/softserve/academy/spaced/repetition/repository/DeckRatingRepository.java
- src/main/java/com/softserve/academy/spaced/repetition/service/CardRatingService.java
- src/main/java/com/softserve/academy/spaced/repetition/service/DeckRatingService.java
Now authorized user can set rating for any deck.
I deleted column "deckId" from table "CardRating" because rating of deck not depends of rating of cards.
Also added table "DeckRating".
That's why you must create new tables (change parameter "validate" to "create" in application.yml and start application).
> ORLP-183.Implement setting of deck rating(back end).

- src/main/java/com/softserve/academy/spaced/repetition/controller/CourseController.java
Front-end realisation of redirecting should be used to make this work. I've already added it to pull request as well.
> ORLP-158. Self link has been fixed.

- src/main/java/com/softserve/academy/spaced/repetition/controller/DeckRatingController.java
- src/main/java/com/softserve/academy/spaced/repetition/domain/DeckRating.java
It was imposible to save DeckRating in database because of type of Id(it was long, I changed it to Long).
Also getter "getId()" in domain "DeckRating" was returning null, so I fixed it too.
> ORLP-188. Fix controller DeckRatingController and domain DeckRating.

- src/main/java/com/softserve/academy/spaced/repetition/controller/CourseController.java
- src/main/java/com/softserve/academy/spaced/repetition/controller/ExceptionHandlerController.java
- src/main/java/com/softserve/academy/spaced/repetition/exceptions/SameDeckInCourseException.java
- src/main/java/com/softserve/academy/spaced/repetition/service/CourseService.java
Fixed ability to add same deck to the course more than once.
> ORLP-185.Fixed ability to add same deck to the course more than once

- src/main/java/com/softserve/academy/spaced/repetition/controller/ExceptionHandlerController.java
> ORLP-185.Change status HTTP response

- src/main/java/com/softserve/academy/spaced/repetition/controller/DeckController.java
- src/main/java/com/softserve/academy/spaced/repetition/service/DeckService.java
In controller method I fixed mapping now it is the save url, and in method create, and fix mistake with deck and newDeck, build link for this now. I separate some methods temporarily for example createNewDeckAdmin and createNewDeck in server, because it is used in other method of controller which is not mine.
> ORLP-173 Controllers with url deck for admin fixed

- src/test/java/com/softserve/academy/spaced/repetition/controller/CourseRatingControllerTest.java
This is an example of Controller unit test.
By the way, @vldmr1703, the unit test shows that your controller returns wrong links.
> ORLP-195. Course rating unit test example.

- src/main/java/com/softserve/academy/spaced/repetition/security/FacebookAuthUtil.java
- src/main/java/com/softserve/academy/spaced/repetition/security/GoogleAuthUtil.java
- src/main/java/com/softserve/academy/spaced/repetition/service/RegistrationService.java
I fixed services of registration, because of changes in Account - field learning_regime.
> ORLP-204.Fix registration.

- src/main/java/com/softserve/academy/spaced/repetition/domain/Person.java
- src/main/java/com/softserve/academy/spaced/repetition/service/AccessToUrlService.java
ORLP-222.Redefine methods equals() and hashcode()
> ORLP-222.Redefine methods equals() and hashcode()

- .travis.yml
Now the build results are available at https://travis-ci.org/koldovsky/orlp-server
> ORLP-175. Continuous integration with Travis.

- src/test/java/com/softserve/academy/spaced/repetition/security/JwtTokenUtilTest.java
> ORLP-175. Fixed Jwt token test.

- src/test/java/com/softserve/academy/spaced/repetition/controller/CourseCommentControllerTest.java
ORLP-208.Test for CommentController
> ORLP-208.Test for CommentController

- src/main/java/com/softserve/academy/spaced/repetition/service/CourseCommentService.java
- src/test/java/com/softserve/academy/spaced/repetition/service/CourseCommentServiceTest.java
Added tests for CourseCommentService
> Added tests for CourseCommentService

- src/main/java/com/softserve/academy/spaced/repetition/config/SecurityConfiguration.java
CorsFilter was added to security configuration in order to enavle interaction betwen web and server
> CorsFilter was added to security configuration

- src/main/java/com/softserve/academy/spaced/repetition/service/UserService.java
Passwords were saving in db in plain text.
> ORLP-274.Fixed encode account password

- src/main/java/com/softserve/academy/spaced/repetition/controller/CategoryController.java
- src/main/java/com/softserve/academy/spaced/repetition/domain/Image.java
- src/main/java/com/softserve/academy/spaced/repetition/dto/impl/CategoryDTO.java
- src/main/java/com/softserve/academy/spaced/repetition/dto/impl/ImageDTO.java
- src/main/java/com/softserve/academy/spaced/repetition/repository/ImageRepository.java
- src/main/java/com/softserve/academy/spaced/repetition/service/CategoryService.java
- src/main/java/com/softserve/academy/spaced/repetition/service/ImageService.java
Added possibility to create categories
> ORLP-266.AddedPossibilityToCreateCategories

- src/main/java/com/softserve/academy/spaced/repetition/controller/ExceptionHandlerController.java
> ORLP-401 - @ResponseBody and @ResponseStatus can be used

- src/main/java/com/softserve/academy/spaced/repetition/controller/ExceptionHandlerController.java
- src/main/java/com/softserve/academy/spaced/repetition/security/FacebookAuthUtil.java
- src/main/java/com/softserve/academy/spaced/repetition/security/JwtAuthenticationEntryPoint.java
- src/main/java/com/softserve/academy/spaced/repetition/security/JwtTokenForMail.java
- src/main/java/com/softserve/academy/spaced/repetition/security/service/AuthenticationRestService.java
- src/main/java/com/softserve/academy/spaced/repetition/security/service/JwtUserDetailsService.java
- src/main/resources/application.yml
- src/main/resources/messages.properties
…ked and all messages from them was moved to new message file in resources
> ORLP-426 (Move messages to resource file  config, controller, repository, domain and security)

- src/main/java/com/softserve/academy/spaced/repetition/controller/CourseRatingController.java
- src/main/java/com/softserve/academy/spaced/repetition/controller/DeckCommentController.java
- src/main/java/com/softserve/academy/spaced/repetition/controller/DeckController.java
Refactored DeckController, CourseRatingController and DeckCommentController controllers.
> Closes #224 - Refactor REST API (Part 4)
